/**
 * products-all.js
 * Todos los productos de audio vehicular (Fuente única de verdad).
 */

import CATEGORY_NAMES from '../constants/category_names.js';
import BADGE_NAMES from '../constants/badge_names.js';
import BRAND_NAMES from '../constants/brand_names.js';

import estereo_b52 from '../assets/products_section_pictures/estereo_b52-rm-2025bt.jpeg';
import rackera_2y2_para_pote from '../assets/products_section_pictures/rackera-2y2-para-pote.jpeg';
import pote_taramps_400x4 from '../assets/products_section_pictures/pote_taramps_400x4.jpeg';
import estereo_crown_mustang from '../assets/products_section_pictures/estereo-crown-mustang.jpeg';
import estereo_infinity_tech from '../assets/products_section_pictures/estereo-infinity-tech.jpeg';
import estereo_philco from '../assets/products_section_pictures/estereo-philco.jpeg';
import rackera_2medios_2super from '../assets/products_section_pictures/rackera-2medios-2supertweeter.jpeg';
import rackera_4drivers5041 from '../assets/products_section_pictures/rackera-4drivers5041.jpeg';
import rackera_curva_completa_estereo from '../assets/products_section_pictures/rackera-curva-completa-estereo.jpeg';
import rackera_2driver_2bomber_2tweeter from '../assets/products_section_pictures/rackera-2driver-2bomber-2tweeter.jpeg';
import kit_instalacion_infinity_tech from '../assets/products_section_pictures/kit-de-cables-infinity-4g.jpeg';
import rackera_2y2_chica from '../assets/products_section_pictures/rackera-2y2-chica.jpeg';
import rackera_2driver_26x9pioneer from '../assets/products_section_pictures/rackera-2driver-26x9pioneer.jpeg';
import rackera_2parlantes_2tweeter_jahro from '../assets/products_section_pictures/rackera-2parlantes-2tweeter-jahro.jpeg';
import super_tweeter_blauline from '../assets/products_section_pictures/supertweeter-blauline.jpeg';
import cable_y_griega from '../assets/products_section_pictures/cable-y-griega.jpeg';
import capacitores_tweeter from '../assets/products_section_pictures/capacitores-tweeter.jpeg';
import capacitores_driver from '../assets/products_section_pictures/capacitores-driver.jpeg';
import difusores_de_aluminio from '../assets/products_section_pictures/difusores-de-aluminio.jpeg';
import pote_taramps_800x4 from '../assets/products_section_pictures/pote-taramps-800x4.jpeg';
import medios_de_8_jahro from '../assets/products_section_pictures/medios-de-8-jahro.jpeg';
import driver_jbl_250 from '../assets/products_section_pictures/driver-jbl-250.jpeg';
import difusores_de_plastico_cortos from '../assets/products_section_pictures/difusores-de-plastico-cortos.jpeg';
import subwoofer_pioneer_12p from '../assets/products_section_pictures/subwoofer-pioneer-12p.jpeg';
import rackera_curva_completa_para_pote_bala from '../assets/products_section_pictures/rackera-curva-completa-para-pote-bala.jpeg';
import parlantes_bomber_6x9_con_caja from '../assets/products_section_pictures/parlantes-bomber-6x9-con-caja.jpeg';
import parlantes_jahro_6p from '../assets/products_section_pictures/parlantes-jahro-6p.jpeg';
import parlantes_jahro_5p from '../assets/products_section_pictures/parlantes-jahro-5p.jpeg';
import parlantes_jahro_4p from '../assets/products_section_pictures/parlantes-jahro-4p.jpeg';
import medios_de_6_jahro from '../assets/products_section_pictures/medios-de-6-jahro.jpeg';
import driver_jahro_5041 from '../assets/products_section_pictures/driver-jahro-5041.jpeg';
import driver_jbl_trio from '../assets/products_section_pictures/driver-jbl-trio.jpeg';
import controles_stetsom from '../assets/products_section_pictures/controles-stetsom.jpeg';
import tweeter_jbl_st400_trio from '../assets/products_section_pictures/tweeter-jbl-st400-trio.jpeg';
import tweeter_jbl_st200 from '../assets/products_section_pictures/tweeter-jbl-st200.jpeg';
import woofer_12p_triton from '../assets/products_section_pictures/woofer-12p-triton.jpeg';
import woofer_12p_triton_850rms from '../assets/products_section_pictures/woofer-12p-triton-850rms.jpeg';
import driver_jahro_5042 from '../assets/products_section_pictures/driver-jahro-5042.jpeg';
import pote_sound_digital_400x4 from '../assets/products_section_pictures/pote-sound-digital-400x4.jpeg';
import pote_sound_digital_800x4 from '../assets/products_section_pictures/pote-sound-digital-800x4.jpeg';
import adaptador_imp_jahro from '../assets/products_section_pictures/adaptador-imp-jahro.jpeg';
import adaptador_imp_blauline from '../assets/products_section_pictures/adaptador-imp-blauline.jpeg';
import parlantes_pioneer_300w from '../assets/products_section_pictures/parlantes-pioneer-300w.jpeg';
import rackera_curva_completa_para_pote from '../assets/products_section_pictures/rackera-curva-completa-para-pote.jpeg';
import voltimetro_taramps from '../assets/products_section_pictures/voltimetro-taramps.jpeg';
import cable_rca_svart_4mm_1m from '../assets/products_section_pictures/cable-rca-svart-4mm-1m.jpeg';
import adaptador_imp_maverick from '../assets/products_section_pictures/adaptador-imp-maverick.jpeg';
import rackera_2driver5041_2medios_6p_audiopipe from '../assets/products_section_pictures/rackera-2driver5041-2medios-6p-audiopipe.jpeg';
import parlantes_bomber_5pulgadas from '../assets/products_section_pictures/parlantes-bomber-5pulgadas.jpeg';
import parlantes_pioneer_6_coma_5_pulgadas_280w from '../assets/products_section_pictures/parlantes-pioneer-6.5pulgadas-280w.jpeg';
import rackera_2_6x9_pioneer_2_supertweeter_jahro from '../assets/products_section_pictures/rackera-2-6x9-pioneer-2-supertweeter-jahro.jpeg';
import rackera_2driver_2tweeter_arwen from '../assets/products_section_pictures/rackera-2driver-2tweeter-arwen.jpeg';
import tweeter_bala_ds18_pro_twx2 from '../assets/products_section_pictures/tweeter-bala-ds18-pro-twx2.jpeg';
import medios_de_8_pulgadas_ap from '../assets/products_section_pictures/medios-de-8-pulgadas-ap.jpeg';
import medios_de_8_pulgadas_wild_sound from '../assets/products_section_pictures/medios-de-8-pulgadas-wild-sound.jpeg';
import estereo_car_mp3_player from '../assets/products_section_pictures/estereo-car-mp3-player.jpeg';
import rackera_2_medios_de_6_jahro_2_driver_jahro_5042 from '../assets/products_section_pictures/rackera-2-medios-de-6-jahro-2-driver-jahro-5042.jpeg';
import driver_jahro_atq_250 from '../assets/products_section_pictures/driver-jahro-atq-250.jpeg';
import rackera_2_medios_de_8_2_driver_5042 from '../assets/products_section_pictures/rackera-2-medios-de-8-2-driver-5042.jpeg';
import pantalla_pioneer_DMH_A5650BT from '../assets/products_section_pictures/pantalla-pioneer-DMH-A5650BT.jpeg';
import tweeter_jahro_yp307 from '../assets/products_section_pictures/tweeter-jahro-yp307.jpeg';

export const ALL_PRODUCTS = [
    {
        id: 1,
        name: 'B52 RM-2025BT 4x25 watts',
        category: CATEGORY_NAMES.ESTEREOS,
        brand: BRAND_NAMES.B52,
        image: estereo_b52,
        description: 'Receptor de audio digital con Bluetooth.',
        badge: BADGE_NAMES.BEST_SELLER,
        price: '$70.000',
        base_price: '$50.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null,
        isFeatured: true
    },
    {
        id: 2,
        name: 'Rackera 2 drivers Jahro 5042 250W MAX y 2 super tweeters',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2y2_para_pote,
        description: 'Rackera 2 drivers Jahro 5042 250 watts y 2 super tweeters Jahro',
        badge: BADGE_NAMES.BEST_SELLER,
        price: '$160.000',
        base_price: '$120.000',
        state: true,
        weight: 7.9,
        height: 20,
        width: 62,
        depth: 23,
        isFeatured: true
    },
    {
        id: 3,
        name: 'Taramps 400.4',
        category: CATEGORY_NAMES.POTENCIAS,
        brand: BRAND_NAMES.TARAMPS,
        image: pote_taramps_400x4,
        description: 'Potencia Taramps 400x4 4 canales 400 watts RMS',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$90.000',
        base_price: '$70.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null,
        isFeatured: true
    },
    {
        id: 4,
        name: 'Tweeter JBL ST400 Trio',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JBL,
        image: tweeter_jbl_st400_trio,
        description: 'Tweeter JBL ST400 Trio de 200w rms',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$110.000',
        base_price: '$91.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null,
        isFeatured: true
    },
    {
        id: 5,
        name: 'Driver JBL D250-X',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JBL,
        image: driver_jbl_250,
        description: 'Driver JBL D250-X',
        badge: BADGE_NAMES.RECOMMENDED,
        price: '$90.000',
        base_price: '$65.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null,
        isFeatured: true
    },
    {
        id: 6,
        name: 'Rackera 2 driver Jahro 5041 y 2 tweeter Jahro',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2y2_chica,
        description: 'Rackera 2 driver Jahro 5041 de 150W MAX y 2 tweeter Jahro',
        badge: BADGE_NAMES.BEST_SELLER,
        price: '$85.000',
        base_price: '$55.000',
        state: true,
        weight: 4,
        height: 18,
        width: 60,
        depth: 22,
        isFeatured: true
    },
    {
        id: 7,
        name: 'Kit instalación Infinity Tech 8 GA',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: BRAND_NAMES.INFINITY_TECH,
        image: kit_instalacion_infinity_tech,
        description: 'Kit de cableado completo calibre 8 GA. Incluye cable de poder, tierra, señal RCA y fusible.',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$25.000',
        base_price: '$22.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null,
        isFeatured: true
    },
    {
        id: 8,
        name: 'Sony XAV-AX5500',
        category: CATEGORY_NAMES.ESTEREOS,
        brand: BRAND_NAMES.SONY,
        image: null,
        description: 'Pantalla táctil de 6.95" con Apple CarPlay, Android Auto, WebLink Cast y Bluetooth.',
        badge: null,
        price: '$140.000',
        base_price: '$88.000',
        state: false,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 9,
        name: 'Rackera 2 medios de 8 pulgadas y 2 super tweeters Jahro',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2medios_2super,
        description: 'Rackera 2 medios de 8 pulgadas marca Jahro y 2 super tweeters Jahro',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$140.000',
        base_price: '$95.000',
        state: true,
        weight: 10,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 10,
        name: 'Rackera 4 drivers Jahro 5041',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_4drivers5041,
        description: 'Rackera 4 drivers Jahro 5041 de 150 watts',
        badge: null,
        price: '$125.000',
        base_price: '$76.000',
        state: true,
        weight: 5,
        height: 18,
        width: 71,
        depth: 22
    },
    {
        id: 11,
        name: 'Rackera 2 drivers, 2 medios y 2 tweeters',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_curva_completa_estereo,
        description: 'Rackera 2 drivers jahro 5041, 2 medios jahro y 2 tweeters Jahro',
        badge: BADGE_NAMES.BEST_SELLER,
        price: '$170.000',
        base_price: '$120.000',
        state: true,
        weight: 8,
        height: 22,
        width: 99,
        depth: 23
    },
    {
        id: 12,
        name: 'Rackera 2 drivers, 2 parlantes y 2 tweeters',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2driver_2bomber_2tweeter,
        description: 'Rackera 2 drivers Jahro, 2 parlantes Bomber de 6" y 2 tweeters marca Jahro',
        badge: BADGE_NAMES.SALE,
        price: '$75.000',
        base_price: '$46.000',
        state: false,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 13,
        name: 'Estereo philco CSP2950BT',
        category: CATEGORY_NAMES.ESTEREOS,
        brand: BRAND_NAMES.PHILCO,
        image: estereo_philco,
        description: 'Estereo Philco con Bluetooth, USB, Manos Libres',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$50.000',
        base_price: '$30.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 14,
        name: 'Rackera 2 drivers y 2 parlantes 6x9 Pioneer',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2driver_26x9pioneer,
        description: 'Rackera 2 drivers Jahro 5041 de 150 watts y 2 parlantes Pioneer 6x9',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$160.000',
        base_price: '$120.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 15,
        name: 'Rackera 2 parlantes Jahro y 2 tweeters Jahro',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2parlantes_2tweeter_jahro,
        description: 'Rackera 2 parlantes de 6" marca Jahro y 2 tweeters marca Jahro',
        badge: null,
        price: '$85.000',
        base_price: '$50.000',
        state: true,
        weight: 4,
        height: 18,
        width: 60,
        depth: 22
    },
    {
        id: 16,
        name: 'Super Tweeter Blauline BT-304',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.BLAULINE,
        image: super_tweeter_blauline,
        description: 'Super Tweeter Blauline 1.8 Super Bullet',
        badge: null,
        price: '$30.000',
        base_price: '$18.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 17,
        name: 'Cable y Griega',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: null,
        image: cable_y_griega,
        description: 'Cable y Griega - 1 rca hembra a 2 rca macho',
        badge: null,
        price: '$5.000',
        base_price: '$2.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 18,
        name: 'Capacitores para Tweeter',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: null,
        image: capacitores_tweeter,
        description: 'Capacitores para Tweeter',
        badge: null,
        price: '$2.500',
        base_price: '$1.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 19,
        name: 'Capacitores para Driver',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: null,
        image: capacitores_driver,
        description: 'Capacitores para Driver',
        badge: null,
        price: '$2.500',
        base_price: '$1.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 20,
        name: 'Difusores de Aluminio',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: null,
        image: difusores_de_aluminio,
        description: 'Difusores de Aluminio para Driver',
        badge: null,
        price: '$37.000',
        base_price: '$28.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 21,
        name: 'Potencia Taramps 800.4',
        category: CATEGORY_NAMES.POTENCIAS,
        brand: BRAND_NAMES.TARAMPS,
        image: pote_taramps_800x4,
        description: 'Potencia Taramps 800.4 4 canales 800 watts RMS',
        badge: null,
        price: '$180.000',
        base_price: '$160.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 22,
        name: 'Medio de 8 pulgadas Jahro',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JAHRO,
        image: medios_de_8_jahro,
        description: 'Medio de 8 pulgadas marca Jahro',
        badge: null,
        price: '$32.000',
        base_price: '$22.500',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 23,
        name: 'Estereo Infinity Tech',
        category: CATEGORY_NAMES.ESTEREOS,
        brand: BRAND_NAMES.INFINITY_TECH,
        image: estereo_infinity_tech,
        description: 'Estereo Infinity Tech con Bluetooth, USB, MP3',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$40.000',
        base_price: '$22.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 24,
        name: 'Difusores de Plástico Cortos',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: null,
        image: difusores_de_plastico_cortos,
        description: 'Difusores de Plástico Cortos',
        badge: null,
        price: '$3.800',
        base_price: '$2.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 25,
        name: 'Subwoofer Pioneer 12 pulgadas',
        category: CATEGORY_NAMES.SUBWOOFERS,
        brand: BRAND_NAMES.PIONEER,
        image: subwoofer_pioneer_12p,
        description: 'Subwoofer Pioneer 12 pulgadas doble bobina TS-W312D4 1600w Max / 500w RMS',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$200.000',
        base_price: '$USD 55',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 26,
        name: 'Rackera Curva 2 medios bala, 2 drivers 250 y 2 super tweeters',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_curva_completa_para_pote_bala,
        description: 'Rackera Curva 2 medios bala, 2 drivers 250 y 2 super tweeters',
        badge: null,
        price: '$290.000',
        base_price: '$230.000',
        state: true,
        weight: null,
        height: 22,
        width: 99,
        depth: 23
    },
    {
        id: 27,
        name: 'Parlantes Bomber 6x9 con Cajas individuales (el par)',
        category: CATEGORY_NAMES.PARLANTES,
        brand: BRAND_NAMES.BOMBER,
        image: parlantes_bomber_6x9_con_caja,
        description: 'Parlantes Bomber 6x9 con Cajas individuales',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$99.000',
        base_price: '$67.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 28,
        name: 'Parlantes Jahro 6 pulgadas (el par)',
        category: CATEGORY_NAMES.PARLANTES,
        brand: BRAND_NAMES.JAHRO,
        image: parlantes_jahro_6p,
        description: 'Parlantes Jahro 6 pulgadas',
        badge: BADGE_NAMES.SALE,
        price: '$32.000',
        base_price: '$18.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 29,
        name: 'Parlantes Jahro 5 pulgadas (el par)',
        category: CATEGORY_NAMES.PARLANTES,
        brand: BRAND_NAMES.JAHRO,
        image: parlantes_jahro_5p,
        description: 'Parlantes Jahro 5 pulgadas',
        badge: null,
        price: '$32.000',
        base_price: '$17.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 30,
        name: 'Parlantes Jahro 4 pulgadas (el par)',
        category: CATEGORY_NAMES.PARLANTES,
        brand: BRAND_NAMES.JAHRO,
        image: parlantes_jahro_4p,
        description: 'Parlantes Jahro 4 pulgadas',
        badge: null,
        price: '$32.000',
        base_price: '$16.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 31,
        name: 'Medio de 6" Jahro',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JAHRO,
        image: medios_de_6_jahro,
        description: 'Medio de 6" marca Jahro',
        badge: null,
        price: '$27.000',
        base_price: '$20.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 32,
        name: 'Driver Jahro 5041',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JAHRO,
        image: driver_jahro_5041,
        description: 'Driver Jahro 5041 de 150 watts',
        badge: null,
        price: '$22.000',
        base_price: '$12.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 33,
        name: 'Driver JBL Trio',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JBL,
        image: driver_jbl_trio,
        description: 'Driver JBL D250 Trio de 200w rms',
        badge: BADGE_NAMES.TOP_QUALITY,
        price: '$135.000',
        base_price: '$110.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 34,
        name: 'Controlador de Sonido Stetsom',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: BRAND_NAMES.STETSOM,
        image: controles_stetsom,
        description: 'Controlador de Sonido Stetsom',
        badge: BADGE_NAMES.NEW,
        price: '$50.000',
        base_price: '$35.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 35,
        name: 'Estereo Crown Mustang DMR-3000BT',
        category: CATEGORY_NAMES.ESTEREOS,
        brand: BRAND_NAMES.CROWN_MUSTANG,
        image: estereo_crown_mustang,
        description: 'Estereo Crown Mustang con Bluetooth, USB, MP3',
        badge: null,
        price: '$65.000',
        base_price: '$45.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 36,
        name: 'Tweeter JBL ST200',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JBL,
        image: tweeter_jbl_st200,
        description: 'Tweeter JBL ST200 de 100w rms',
        badge: null,
        price: '$55.000',
        base_price: '$41.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 37,
        name: 'Woofer Triton 12 Pulgadas 620rms',
        category: CATEGORY_NAMES.SUBWOOFERS,
        brand: BRAND_NAMES.TRITON,
        image: woofer_12p_triton,
        description: 'Woofer Triton 12 Pulgadas TR 620 8 ohm 620w Rms 1240w pmpo',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$250.000',
        base_price: '$195.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 38,
        name: 'Woofer Triton 12 Pulgadas 850rms',
        category: CATEGORY_NAMES.SUBWOOFERS,
        brand: BRAND_NAMES.TRITON,
        image: woofer_12p_triton_850rms,
        description: 'Woofer Triton Medio Grave 850w Rms 8 Ohm Tr 850 Negro',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$340.000',
        base_price: '$265.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 39,
        name: 'Driver Jahro 5042 200w MAX',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JAHRO,
        image: driver_jahro_5042,
        description: 'Driver Jahro 5042 250 watts max 40w Rms',
        badge: null,
        price: '$50.000',
        base_price: '$35.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 40,
        name: 'Potencia Sound Digital 400.4',
        category: CATEGORY_NAMES.POTENCIAS,
        brand: BRAND_NAMES.SOUND_DIGITAL,
        image: pote_sound_digital_400x4,
        description: 'Potencia Sound Digital 400.4 400w Rms 4 canales',
        badge: BADGE_NAMES.SALE,
        price: '$100.000',
        base_price: '$80.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 41,
        name: 'Potencia Sound Digital 800.4',
        category: CATEGORY_NAMES.POTENCIAS,
        brand: BRAND_NAMES.SOUND_DIGITAL,
        image: pote_sound_digital_800x4,
        description: 'Potencia Sound Digital 800.4 800w Rms 4 canales',
        badge: null,
        price: '$180.000',
        base_price: '$160.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 42,
        name: 'Adaptador de Impedancia Jahro',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: BRAND_NAMES.JAHRO,
        image: adaptador_imp_jahro,
        description: 'Adaptador Conversor De Impedancia Regulable Jahro',
        badge: null,
        price: '$14.500',
        base_price: '$9.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 43,
        name: 'Adaptador de Impedancia Blauline',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: BRAND_NAMES.BLAULINE,
        image: adaptador_imp_blauline,
        description: 'Adaptador De Impedancia 4 Canales Salida Remoto Blauline',
        badge: null,
        price: '$25.000',
        base_price: '$15.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 44,
        name: 'Parlantes Pioneer 300W MAX',
        category: CATEGORY_NAMES.PARLANTES,
        brand: BRAND_NAMES.PIONEER,
        image: parlantes_pioneer_300w,
        description: 'Pioneer TS G1620F Negro 6.5 Pulgadas Potencia Máxima 300W',
        badge: BADGE_NAMES.TOP_QUALITY,
        price: '$88.000',
        base_price: '$68.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 45,
        name: 'Rackera Curva 2 Medios de 8 pulgadas, 2 Drivers 250 y 2 Super Tweeters',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_curva_completa_para_pote,
        description: 'Rackera Curva 2 Medios de 8 pulgadas, 2 Drivers 250 y 2 Super Tweeters',
        badge: null,
        price: '$260.000',
        base_price: '$195.000',
        state: true,
        weight: null,
        height: 22,
        width: 99,
        depth: 23
    },
    {
        id: 46,
        name: 'Voltimetro automotivo Taramps',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: BRAND_NAMES.TARAMPS,
        image: voltimetro_taramps,
        description: 'Voltimetro automotivo Taramps VTR 1000',
        badge: null,
        price: '$27.000',
        base_price: '$15.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 47,
        name: 'Cable RCA Svart 4mm 1m',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: BRAND_NAMES.SVART,
        image: cable_rca_svart_4mm_1m,
        description: 'Cable RCA Svart 4mm 1m',
        badge: null,
        price: '$17.000',
        base_price: '$12.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 48,
        name: 'Adaptador de Impedancia Maverick',
        category: CATEGORY_NAMES.ACCESORIOS,
        brand: BRAND_NAMES.MAVERICK,
        image: adaptador_imp_maverick,
        description: 'Adaptador de Impedancia Maverick universal',
        badge: null,
        price: '$14.500',
        base_price: '$9.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 49,
        name: 'Rackera 2 Drivers Jahro y 2 Medios de 6 pulgadas AudioPipe',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2driver5041_2medios_6p_audiopipe,
        description: 'Rackera 2 Drivers Jahro 5041, 2 Medios de 6 pulgadas AudioPipe 250W MAX',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$165.000',
        base_price: '$98.000',
        state: true,
        weight: 7,
        height: 18,
        width: 71,
        depth: 22
    },
    {
        id: 50,
        name: 'Parlantes Bomber 5 pulgadas',
        category: CATEGORY_NAMES.PARLANTES,
        brand: BRAND_NAMES.BOMBER,
        image: parlantes_bomber_5pulgadas,
        description: 'Parlantes Bomber 5 pulgadas 65W RMS',
        badge: null,
        price: '$50.000',
        base_price: '$35.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 51,
        name: 'Parlantes Pioneer 6.5 pulgadas 280W MAX',
        category: CATEGORY_NAMES.PARLANTES,
        brand: BRAND_NAMES.PIONEER,
        image: parlantes_pioneer_6_coma_5_pulgadas_280w,
        description: 'Parlantes Pioneer 6.5 pulgadas 280W MAX',
        badge: BADGE_NAMES.OUT_OF_STOCK,
        price: '$68.000',
        base_price: '$55.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 52,
        name: 'Rackera 2 6x9 Pioneer y 2 Super Tweeter Jahro',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2_6x9_pioneer_2_supertweeter_jahro,
        description: 'Rackera 2 6x9 Pioneer de 500W MAX y 2 Super Tweeter Jahro',
        badge: null,
        price: '$170.000',
        base_price: '$120.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 53,
        name: 'Rackera 2 drivers y 2 tweeter Arwen',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2driver_2tweeter_arwen,
        description: 'Rackera 2 Drivers y 2 Tweeter Arwen',
        badge: null,
        price: '$85.000',
        base_price: '$55.000',
        state: true,
        weight: 4,
        height: 18,
        width: 60,
        depth: 22
    },
    {
        id: 54,
        name: 'Tweeter Bala DS18 Pro TWX2 (el par)',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.DS18,
        image: tweeter_bala_ds18_pro_twx2,
        description: 'Tweeter Bala DS18 Pro TWX2 de 3.78 pulgadas',
        badge: null,
        price: '$70.000',
        base_price: '$50.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 55,
        name: 'Medios de 8 pulgadas AudioPipe (el par)',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.AUDIOPIPE,
        image: medios_de_8_pulgadas_ap,
        description: 'Medios de 8 pulgadas AudioPipe de 300Watts MAX',
        badge: BADGE_NAMES.RECOMMENDED,
        price: '$105.000',
        base_price: '$80.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 56,
        name: 'Medios de 8 pulgadas Wild Sound (el par)',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.WILD_SOUND,
        image: medios_de_8_pulgadas_wild_sound,
        description: 'Medios de 8 pulgadas Wild Sound de 150Watts MAX',
        badge: BADGE_NAMES.NEW,
        price: '$65.000',
        base_price: '$45.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 57,
        name: 'Estereo Car MP3 Player',
        category: CATEGORY_NAMES.ESTEREOS,
        brand: null,
        image: estereo_car_mp3_player,
        description: 'Estereo Car MP3 Player de 1 Din, Bluetooth, USB, FM, hands free, AUX, Control remoto.',
        badge: BADGE_NAMES.SALE,
        price: '$26.000',
        base_price: '$16.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 58,
        name: 'Rackera 2 medios de 6 Jahro y 2 Driver Jahro 5042',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2_medios_de_6_jahro_2_driver_jahro_5042,
        description: 'Rackera 2 medios de 6 Jahro, 2 Driver Jahro 5042 200W MAX',
        badge: null,
        price: '$180.000',
        base_price: '$140.000',
        state: true,
        weight: 7,
        height: 18,
        width: 71,
        depth: 22
    },
    {
        id: 59,
        name: 'Driver Jahro ATQ02 250W MAX',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JAHRO,
        image: driver_jahro_atq_250,
        description: 'Driver Jahro ATQ-250 de 250 Watts MAX - piezo eléctrico',
        badge: null,
        price: '$12.000',
        base_price: '$8.500',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 60,
        name: 'Rackera 4 driver Jahro ATQ02 250W',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_4drivers5041,
        description: 'Rackera 4 driver Jahro ATQ02 250W MAX - Piezo Eléctrico',
        badge: BADGE_NAMES.BARGAIN,
        price: '$85.000',
        base_price: '$47.000',
        state: true,
        weight: 3.7,
        height: 18,
        width: 71,
        depth: 22
    },
    {
        id: 61,
        name: 'Rackera 2 driver Jahro ATQ02 250W y 2 Tweeter',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2y2_chica,
        description: 'Rackera con 2 Driver JAhro ATQ02 piezoelectrico 250W y 2 Tweeter',
        badge: BADGE_NAMES.SALE,
        price: '$75.000',
        base_price: '$37.000',
        state: true,
        weight: 3,
        height: 18,
        width: 60,
        depth: 22
    },
    {
        id: 62,
        name: 'Rackera 2 medios de 8 y 2 driver 5042 Jahro',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2_medios_de_8_2_driver_5042,
        description: 'Rackera 2 medios de 8 pulgadas Jahro y 2 Driver Jahro 5042',
        badge: null,
        price: '$195.000',
        base_price: '$145.000',
        state: true,
        weight: 9,
        height: 22,
        width: 79,
        depth: 22
    },
    {
        id: 63,
        name: 'Pantalla Pioneer DMH-A5650BT',
        category: CATEGORY_NAMES.ESTEREOS,
        brand: BRAND_NAMES.PIONEER,
        image: pantalla_pioneer_DMH_A5650BT,
        description: 'Pioneer DMH-A5650BT - Pantalla con radio, Bluetooth, Apple car play y Android Auto Inalámbrico',
        badge: null,
        price: '$280.000',
        base_price: '$230.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 64,
        name: 'Tweeter Jahro YP307 250W',
        category: CATEGORY_NAMES.COMPONENTES,
        brand: BRAND_NAMES.JAHRO,
        image: tweeter_jahro_yp307,
        description: 'Tweeter Jahro YP-307 Piezoeléctrico',
        badge: BADGE_NAMES.SALE,
        price: '$8.500',
        base_price: '$3.000',
        state: true,
        weight: null,
        height: null,
        width: null,
        depth: null
    },
    {
        id: 65,
        name: 'Rackera 2 medios Jahro de 6 pulgadas y 2 driver Jahro 5041',
        category: CATEGORY_NAMES.RACKERAS,
        brand: null,
        image: rackera_2_medios_de_6_jahro_2_driver_jahro_5042,
        description: 'Rackera 2 medios de 6 pulgadas Jahro y 2 Driver Jahro 5041 de 150W MAX',
        badge: BADGE_NAMES.NEW,
        price: '$128.000',
        base_price: '$84.000',
        state: true,
        weight: 6,
        height: 18,
        width: 71,
        depth: 22
    }
];